# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :selinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          ENV['LC_ALL']="en_US.UTF-8"

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
            vb.name = "selinux"
          end
          
#          box.vm.synced_folder "scripts", "/vagrant"
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
          
          box.vm.provision "shell", path: "./scripts/install.sh"
          
#           box.vm.provision "ansible" do |ansible|
#             ansible.playbook = "pam.yml"
#           end

      end
  end
end
